services:
  - type: web
    name: blooddonationbaguio
    env: docker
    autoDeploy: true
    branch: main
    plan: free
    preDeployCommand: "php seed_production_db.php; echo 'Pre-deploy script finished. Listing files:'; ls -la"