services:
  - type: web
    name: blooddonationbaguio
    env: docker
    autoDeploy: true
    branch: main
    plan: free
    healthCheckPath: "/health.php"
    preDeployCommand: "php seed_production_db.php"